### ISSUE TITLE
Smart Subjects phpBB 3.3.0

### ISSUE THREAD

**Issue by Herve-be** [iMattPro/smartsubjects#6]
Hi,
Does not work anymore under 3.3.0 : the button "copy subject to all posts is even no more present.
Is there a solution ?
Thanks

**Comment by iMattPro** [comment]
There is no such button.

There is an option only, based on forum permissions, only available to admins and mods and only when editing the first post.

Works fine in every version of phpBB since extensions were introduced. 

![Screen Shot 2020-04-05 at 12 59 17 PM](https://user-images.githubusercontent.com/303711/78508645-49050e80-773d-11ea-81dd-73a0688fc917.png)

https://www.phpbb.com/customise/db/extension/smart_subjects/support

**Comment by Herve-be** [comment]
Sorry, I wrote "Button" instead of "option".
I'm admin of the forum www.leforumrecifal.com
Here are 2 examples of first post editing.
For the first one I can propagate the title (Remplacer le titre de toutes les réponses)
for the second one I cannot : why ?

![Remplacer](https://user-images.githubusercontent.com/42873018/78538585-84f9ab80-77f1-11ea-803e-5bf4f4acf96a.jpg)
